parameters:
#    jaxara_project_shoeb.example.class: Jaxara\Project\ShoebBundle\Example

services:
#    jaxara_project_shoeb.example:
#        class: %jaxara_project_shoeb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
