parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sf_proj
    database_user: root
    database_password: jax_root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b7b71143c3adc9779e74d825d5dc8a689b0182f3
    database_path: null
