pantheon_user:
    resource: "@PantheonUserBundle/Resources/config/routing.yml"
    prefix:   /

jaxara_project_shoeb:
    resource: "@JaxaraProjectShoebBundle/Resources/config/routing.yml"
    prefix:   /